name: Helm Pull Action
description: Pull a helm chart to a local directory

inputs:
  chart-and-tag: 
    description: Helm Chart and tag to pull
    required: true
  relative-target-directory:
    description: Relative directory to use when saving the chart locally
    required: false
    default: helmchart
  ecr-login:
    description: "Values: true/false. Require ECR Login to pull"
    required: false
    default: "false"
  aws-account-id:
    description: Account ID used for ECR login
    required: false
  aws-region:
    description: Region used for ECR login
    required: false
    default: us-east-1
outputs:
  chart-path: 
    description: Path to the locally pulled chart
    value: ${{ steps.pull-chart.outputs.chart-path }}

runs:
  using: "composite"
  steps:
    - id: pull-chart
      env:
        INPUT_CHART_AND_TAG: ${{ inputs.chart-and-tag }}
        INPUT_TARGET_DIRECTORY: ${{ inputs.target-directory }}
        INPUT_ECR_LOGIN: ${{ inputs.ecr-login }}
        INPUT_AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
      run: ${{ github.action_path }}/action.sh
      shell: bash