
ingress-nginx:
  controller:
    config:
      ssl-redirect: "false"
#      error-log-level: "info"
    service:
      type: NodePort

air-ui-oss:
  enabled: true
  deployment:
    service:
      type: NodePort
      nodePort: 31884
    ingress:
      hostname: labs.air.ui.oss.com

mosquitto:
  enabled: true
  service:
    type: NodePort
  ports:
    mqtt:
      port: 1883
      nodePort: 31883
#  authentication:
#    passwordEntries: |-
#      mqtt_admin:$7$101$jP6Xhsu/Ez1c4fWy$F4j7SDBuDaWzWL8FBEqS/Prbn1aB0RBjN8gjpuN8C4OrFSA+EnUbmj0stWiU37Gve1ukRRMqHd38wjlpuNlb0g==

#    passwordFilePath: "/etc/mosquitto/passwordfile"
#  authorization:
    #acls: ""
    # To use authorizations with mosquitto, you can set a list of per user or pattern-based rules.
    # reference https://mosquitto.org/man/mosquitto-conf-5.html for further information.
    # For example:
#    acls: |-
#        user mqtt_admin
#        topic readwrite mqtt_admin/#
 
dgraph:
  enabled: true
  ratel:
    enabled: true
    service:
      type: NodePort
    ingress:
      enabled: true
      hostname: localhost.ratel
  zero:
    replicaCount: 1
    persistence:
      size: 1Gi
  alpha:
    replicaCount: 1
    service:
      type: NodePort
    ingress:
      enabled: true
      hostname: localhost.alpha
    persistence:
      size: 1Gi
    extraFlags: "--security whitelist=172.17.0.0:172.20.0.0 -v=3"



  air-cors-anywhere:
    deployment:
      service:
        type: NodePort

  basicauth:
    name: air-basic-auth
    secret: YWRtaW46JGFwcjEkSExTWWJiaU8kQTRsc3UvNThmTjFrUGIvZXBta2UuLgo=