name: Test helm-oci-pull-action

on: 
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  test-action:
    name: Test helm-pull-action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Pull Helm Chart
        id: helm-pull
        uses: ./
        with:
          chart-and-tag: public.ecr.aws/karpenter/karpenter

      - name: List chart files
        run: ls ${{ steps.helm-pull.outputs.chart-path }}
